services:
  traefik-docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: traefik-docker-proxy
    restart: always
    environment:
      CONTAINERS: 1
    ports:
      - "2375:2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    name: traefik-docker-proxy
